name: Welcome First-Time Contributor

on:
  pull_request:
    types: [ opened ]

permissions:
  pull-requests: write
  issues: read

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
      - name: Greet first-time contributor
        uses: actions/github-script@v7
        with:
          script: |
            // Check if this is the user's first contribution
            const { data: pullRequests } = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              creator: context.payload.pull_request.user.login,
              state: 'all'
            });

            const { data: issues } = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              creator: context.payload.pull_request.user.login,
              state: 'all'
            });

            const isFirstContribution = pullRequests.length === 1 && issues.length === 0;

            if (isFirstContribution) {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.payload.pull_request.number,
                body: `👋 Hello @${context.payload.pull_request.user.login}! Thanks for your first Pull Request 🎉

            We really appreciate your contribution to this project.

            A maintainer will review your PR soon 🚀`
              });
            }
